const questions=[
{q:"You receive an email saying your account will be closed in 10 minutes unless you click a link. What should you do?",o:["Click immediately","Reply with your password","Verify through the organization's official website","Forward it to friends"],a:2,e:"The message uses urgency and a link. Independently access the legitimate website and verify the situation."},
{q:"Which is a common sign of phishing?",o:["Unexpected urgency","A normal conversation","An expected email","A message you requested"],a:0,e:"Urgency is commonly used to pressure people into acting without verifying."},
{q:"What does smishing refer to?",o:["Phishing through phone calls","Phishing through SMS/text messages","Phishing through websites","Phishing through physical mail"],a:1,e:"Smishing is phishing delivered through SMS or text messages."},
{q:"What is social engineering?",o:["Designing a website","Manipulating people to reveal information or perform actions","Encrypting a file","Installing an operating system"],a:1,e:"Social engineering uses deception or manipulation to influence people."},
{q:"HTTPS by itself proves that a website is legitimate.",o:["True","False"],a:1,e:"HTTPS protects the connection, but it does not by itself prove the site's identity."},
{q:"Which information should you never provide in response to an unexpected phishing message?",o:["Password","OTP","Banking information","All of the above"],a:3,e:"Unexpected requests for passwords, OTPs, or banking information should be treated with caution."},
{q:"Someone calls claiming to be from your bank and asks for your OTP. What should you do?",o:["Give the OTP","Verify through an official bank channel first","Give only the first half","Send your password instead"],a:1,e:"Don't disclose OTPs to unexpected callers. Independently verify the request."},
{q:"Which tactic tries to make you act without thinking?",o:["Urgency","Normal communication","Documentation","Encryption"],a:0,e:"Urgency creates pressure and reduces the chance that the victim will verify the request."},
{q:"You receive a suspicious email with an unexpected attachment. What is the safest response?",o:["Open it to check","Forward it","Don't open it and verify the sender","Download it first"],a:2,e:"Unexpected attachments can be risky. Verify the sender and context before opening anything."},
{q:"What is the best general rule when you receive a suspicious message?",o:["Act quickly","Trust the displayed sender name","Stop, think, and verify","Click the link to investigate"],a:2,e:"Stopping, thinking, and independently verifying reduces the chance of falling for phishing."}
];
const qc=document.getElementById("quiz-container");
questions.forEach((x,i)=>{const b=document.createElement("div");b.className="quiz-question";b.innerHTML=`<h3>Question ${i+1}</h3><p><strong>${x.q}</strong></p>`+x.o.map((v,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${v}</label>`).join("");qc.appendChild(b)});
document.getElementById("submitQuiz").addEventListener("click",()=>{let score=0,un=0;questions.forEach((x,i)=>{const s=document.querySelector(`input[name="q${i}"]:checked`);if(!s)un++;else if(Number(s.value)===x.a)score++});const r=document.getElementById("result");r.style.display="block";r.textContent=un?`Please answer all questions. ${un} question(s) are unanswered.`:`Your score: ${score}/${questions.length} (${Math.round(score/questions.length*100)}%). Review the training sections and try again if needed.`});